---
abstract: 'Code shared by the MaxMind::DB:Reader and MaxMind::DB::Writer modules'
author:
  - 'Dave Rolsky <autarch@urth.org>'
  - 'Olaf Alders <olaf@wundercounter.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MaxMind-DB-Common
requires:
  Data::Dumper::Concise: 0
  DateTime: 0
  Exporter: 0
  Math::Int128: 0
  Moose: 0
  Moose::Role: 0
  Moose::Util::TypeConstraints: 0
  MooseX::StrictConstructor: 0
  autodie: 0
  constant: 0
  namespace::autoclean: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=MaxMind-DB-Common
  repository: git://github.com/maxmind/MaxMind-DB-perl.git
version: 0.3.0
