---
abstract: 'Code shared by the MaxMind DB reader and writer modules'
author:
  - 'Dave Rolsky <drolsky@maxmind.com>'
  - 'Olaf Alders <oalders@maxmind.com>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.131560'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MaxMind-DB-Common
requires:
  Carp: 0
  Data::Dumper::Concise: 0
  DateTime: 0
  Exporter: 0
  List::AllUtils: 0
  Math::Int128: 0
  Moo: 0
  Moo::Role: 0
  MooX::StrictConstructor: 0
  Scalar::Util: 0
  Sub::Quote: 0
  autodie: 0
  constant: 0
  namespace::autoclean: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/maxmind/MaxMind-DB-Common-perl/issues
  repository: git://github.com/maxmind/MaxMind-DB-Common-perl.git
version: 0.031003
x_authority: cpan:TJMATHER
